version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
        environment:
          RACKET_DIR: /usr/local/racket
          RACKET_VERSION: 7.5
    steps:
      - run:
          name: install racket
          command: |
            bash <(curl https://raw.githubusercontent.com/greghendershott/travis-racket/master/install-racket.sh)
            echo 'export PATH=${RACKET_DIR}/bin:${PATH}' >> $BASH_ENV
      - run:
          name: install frog
          command: raco pkg install --auto --no-docs frog
      - run:
          name: install tools
          command: |
            pip install --user pygments
      - run:
          # remove script from install-racket, keep the work_directory empty
          name: cleanup
          command: |
            rm -rf * || exit 0;
      - checkout
      - run: raco frog --build
      - run:
          name: prepare assets
          command: mv assets out
      - add_ssh_keys:
          fingerprints:
            - "13:a6:8c:c2:60:66:a7:06:42:c7:f3:2d:c5:d5:6f:00"
      - run:
          name: deploy
          command: |
            cd out
            git init

            git config user.name "circle-ci"
            git config user.email "yfzhe@user.noreply.github.com"

            git add .
            git commit -m "deploy [skip ci]"

            git push --force --quiet "https://github.com/yfzhe/yfzhe.github.io" master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: source
